{
  "hash": "2a802e7172f5a61b52e135f3f1d41c14",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"The Value of Big Swings\"\nsubtitle: \"Why Bold Experiments Deliver More Value with Less Traffic\"\nauthor: \"Russ Zaliznyak\"\ndate: \"2025-08-29\"\ndescription: >\n  Compares two strategies — guaranteed small wins vs. a single high-variance transformational\n  bet — using 30,000 A/B test simulations. Big Swings run faster and generate far more\n  average value.\ncategories: [AB Testing, Strategy, Simulation]\nexecute:\n  echo: false\n---\n\n\n\n\n# TL/DR\n\nSmart A/B testing helps to maximize business metrics like conversion, retention, and revenue. But experimenters often face a strategic dilemma:\n\n- **Play it safe** with frequent, incremental wins  \n- **Swing big** with fewer, riskier tests that could deliver big rewards  \n\nThis tradeoff is a recurring challenge when traffic is limited and profits need to grow. \n\nThis paper compares two distinct strategies:\n\n1. **Guaranteed Small Wins**: ten low-risk bets with small, consistent gains  \n2. **Big Swing**: single high-variance transformational bet that could flop — or deliver a breakthrough\n\nWhich strategy delivers more value on average?\n\n\n---\n\n# A/B Test Design\n\nTo ground the comparison, I define a base experiment with these parameters:\n\n| Min (Test Days) | Max (Test Days) | Max (Test N) | Post Test N | Baseline | Split |\n|-----------------|-----------------|--------------|-------------|----------|-------|\n| 7               | 20              | 80,000       | 500,000     | 65%      | 50/50 |\n\n<br>\nThis design reflects a plausible A/B test: short duration with a capped sample, followed by rollout to a larger population.  \n\n# Strategy Comparison\n\nThe distributions below define each strategy. Guaranteed Small Wins are modeled as tightly clustered positive effects just above baseline, while Big Swings reflect a broader spread — with many harmful ideas but occasional breakthroughs that deliver big gains.\n\n<style>\nimg.framed { border:1px solid #ddd; border-radius:8px; padding:6px; }\n.tile-label { text-align:center; font-weight:600; margin-bottom:6px; }\n.tile-sub { text-align:center; font-style:italic; font-size:0.9em; margin-bottom:10px; }\n</style>\n\n::: {.columns}\n::: {.column width=\"50%\"}\n<div class=\"tile-label\">Distribution of Guaranteed Small Wins</div>\n![](./big-swings-assets/small.png){fig-alt=\"Expected treatment effects, small wins\" width=\"100%\" .framed}\n\n- Effects densely packed around 100.1  \n- Only small positive effects\n:::\n\n::: {.column width=\"50%\"}\n<div class=\"tile-label\">Distribution of Big Swing</div>\n![](./big-swings-assets/big.png){fig-alt=\"Expected treatment effects, transformational\" width=\"100%\" .framed}\n\n- μ = 99.5, σ = 2.25  \n- 60% harmful ideas  \n- High upside potential\n:::\n:::\n\n## Simulation Framework\n\nEach distribution in the *Strategy Comparison* section represents a **space of ideas**. To evaluate them, I simulate 30,000 A/B tests drawn from each distribution.\n\n- **Condition A (Control):** baseline fixed at 65%, with outcomes fluctuating due to random sampling.  \n- **Condition B (Treatment):** true conversion rate is shifted by a random draw from the chosen distribution.\n\nEven when the treatment is encoded with lift, stochastic variation can make it underperform the control in a given run. Results are aggregated across simulations to compare average marginal impact.\n\n::: {columns}\n\n::: {.column width=\"48%\"}\n\n::: {#b12dd231 .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Simulation Example (Control)\"}\nfrom numpy.random import binomial\n\ntotal_users = int(8e4)\ncontrol_users = int(total_users / 2)\nnumber_days = 20\ncontrol_users_per_day = (\n    control_users / number_days\n)\ncontrol_baseline = 0.65\n\ncontrol_conversions_by_day = binomial(\n    control_users,\n    control_baseline,\n    number_days,\n)\n```\n:::\n\n\n:::\n\n\n::: {.column width=\"48%\"}\n\n::: {#1b4f6b99 .cell execution_count=2}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Simulation Example (Treatment)\"}\nfrom numpy.random import normal\n\ntreatment_users = int(total_users / 2)\ntreatment_users_per_day = (\n    treatment_users / number_days\n)\nindex_to_control = (\n    normal(99.5, 2.5, 1) / 100\n)\ntreatment_mean = (\n    control_baseline * index_to_control\n)\n\ntreatment_conversions_by_day = binomial(\n    treatment_users,\n    treatment_mean,\n    number_days,\n)\n```\n:::\n\n\n:::\n\n\n:::\n\n## Stopping Threshold\n\n**`Expected Loss`** is used as our stopping threshold.\n\n$$\n\\text{Expected Loss} = \\Pr(\\text{harm}) \\times \\mathbb{E}[\\text{Magnitude of Harm}]\n$$\n\nWe refer to expected loss as **`Risk`**, which serves only as the stopping criterion below.  \n\nThe **Risk Threshold = 0.025%** was thoughtfully chosen in advance of the experiment as a balanced stopping point given the parameters of this experiment design.  \n\nFor now the rationale for selection is completely glossed over, but readers are encouraged to ping me for details about its selection. I promise to have a paper on how risk thresholds are selected.\n\n\n## Simulation Evaluation\n\n1. For each simulation, and each day on or after `Min (Test Days)`:\n   - Compute **Risk (expected loss)** for both control and treatment conditions.\n   - Compare each condition's **Risk** to the **Risk Threshold = 0.025%**.\n\n2. Decision rules:\n   - If **only one** condition breaches the threshold → select it as the winner.\n   - If **both** breach → choose the condition with the lower risk.\n   - If **neither** breaches by the end of the test → select the condition with the lowest final risk.\n\n3. After selecting a winner:\n   - Simulate rolling out the winner to the remaining test population and the post-test population, regardless of whether it was truly best.\n\n## Results\n\nAll metrics shown are based on 30,000 simulations and represent expected values, i.e., average outcomes aggregated across all simulated experiments --- with each simulation drawing a random treatment effect from its distribution.\n\n| Metric                         | One Guaranteed Win Experiment | One **Big Swing** Experiment |\n|-------------------------------|-------------------------------|------------------------------|\n| **Mean Run-time**              | N = 59,516 (15 days)          | N = 38,713 (10 days)         |\n| **Projected Mean @ Year-End**  | 65.037% (100.06 ITC)          | 65.390% (100.60 ITC)         |\n| **Marginal Events vs No Test** | 216                           | 2,261                        |\n\n\n<br>\n\nCompared to a **Guaranteed Win** experiment, the **Big Swing** strategy shows clear advantages:\n\n1. Runs ~33% faster on average (10 days vs 15), freeing traffic sooner.  \n2. Produces a higher average outcome per experiment (65.39% vs 65.04%), a meaningful gap at scale.  \n3. Generates ~2,261 additional conversions vs only 216 on average. Marginal events scale directly from the projected mean difference.  \n\nWe need just over 10 **Guaranteed Wins** to average the same effect as one **Big Swing**.\n\n\n# Home Runs Outweigh Strikeouts\n\nHow can a strategy with a 60% strikeout rate still outperform 10 guaranteed wins?  \n\nBecause when a transformational idea hits, it hits big. Smart experiments cut losses early while allowing strong performers to scale --- letting a single home run outweigh several duds.\n\nThat's the asymmetric nature of upside: most variants underperform, but rare wins more than make up the difference. And that's why one Big Swing can match the impact of 10 small wins, while using only a fraction of the traffic.  \n\n::: {#819e29af .cell execution_count=3}\n\n::: {.cell-output .cell-output-display}\n```{=html}\n        <script>\n        window.PlotlyConfig = {MathJaxConfig: 'local'};\n        if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}\n        </script>\n        <script type=\"module\">import \"https://cdn.plot.ly/plotly-3.4.0.min\"</script>\n        \n```\n\nA single high-performing variant can easily outweigh multiple duds, justifying the risk.\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.4.0.min.js\" integrity=\"sha256-KEmPoupLpFyGMyGAiOsiNDbKDKAvxXAn/W+oQa0ZAfk=\" crossorigin=\"anonymous\"></script>                <div id=\"a47c3ac4-8745-4e2a-8f1d-7f19e5a9494d\" class=\"plotly-graph-div\" style=\"height:525px; width:100%;\"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"a47c3ac4-8745-4e2a-8f1d-7f19e5a9494d\")) {                    Plotly.newPlot(                        \"a47c3ac4-8745-4e2a-8f1d-7f19e5a9494d\",                        [{\"marker\":{\"color\":[\"red\",\"red\",\"red\",\"red\",\"green\",\"green\",\"green\"]},\"text\":[\"-274\",\"-200\",\"-250\",\"-390\",\"+1500\",\"+3500\",\"+7300\"],\"textposition\":\"outside\",\"x\":[\"97\",\"98\",\"99\",\"99.5\",\"100.5\",\"101\",\"102\"],\"y\":[-274,-200,-250,-390,1500,3500,7300],\"type\":\"bar\"}],                        {\"template\":{\"data\":{\"barpolar\":[{\"marker\":{\"line\":{\"color\":\"white\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"barpolar\"}],\"bar\":[{\"error_x\":{\"color\":\"#2a3f5f\"},\"error_y\":{\"color\":\"#2a3f5f\"},\"marker\":{\"line\":{\"color\":\"white\",\"width\":0.5},\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"bar\"}],\"carpet\":[{\"aaxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"#C8D4E3\",\"linecolor\":\"#C8D4E3\",\"minorgridcolor\":\"#C8D4E3\",\"startlinecolor\":\"#2a3f5f\"},\"baxis\":{\"endlinecolor\":\"#2a3f5f\",\"gridcolor\":\"#C8D4E3\",\"linecolor\":\"#C8D4E3\",\"minorgridcolor\":\"#C8D4E3\",\"startlinecolor\":\"#2a3f5f\"},\"type\":\"carpet\"}],\"choropleth\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"type\":\"choropleth\"}],\"contourcarpet\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"type\":\"contourcarpet\"}],\"contour\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"type\":\"contour\"}],\"heatmap\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"type\":\"heatmap\"}],\"histogram2dcontour\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"type\":\"histogram2dcontour\"}],\"histogram2d\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"type\":\"histogram2d\"}],\"histogram\":[{\"marker\":{\"pattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2}},\"type\":\"histogram\"}],\"mesh3d\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"type\":\"mesh3d\"}],\"parcoords\":[{\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"parcoords\"}],\"pie\":[{\"automargin\":true,\"type\":\"pie\"}],\"scatter3d\":[{\"line\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scatter3d\"}],\"scattercarpet\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scattercarpet\"}],\"scattergeo\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scattergeo\"}],\"scattergl\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scattergl\"}],\"scattermapbox\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scattermapbox\"}],\"scattermap\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scattermap\"}],\"scatterpolargl\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scatterpolargl\"}],\"scatterpolar\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scatterpolar\"}],\"scatter\":[{\"fillpattern\":{\"fillmode\":\"overlay\",\"size\":10,\"solidity\":0.2},\"type\":\"scatter\"}],\"scatterternary\":[{\"marker\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"type\":\"scatterternary\"}],\"surface\":[{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"},\"colorscale\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"type\":\"surface\"}],\"table\":[{\"cells\":{\"fill\":{\"color\":\"#EBF0F8\"},\"line\":{\"color\":\"white\"}},\"header\":{\"fill\":{\"color\":\"#C8D4E3\"},\"line\":{\"color\":\"white\"}},\"type\":\"table\"}]},\"layout\":{\"annotationdefaults\":{\"arrowcolor\":\"#2a3f5f\",\"arrowhead\":0,\"arrowwidth\":1},\"autotypenumbers\":\"strict\",\"coloraxis\":{\"colorbar\":{\"outlinewidth\":0,\"ticks\":\"\"}},\"colorscale\":{\"diverging\":[[0,\"#8e0152\"],[0.1,\"#c51b7d\"],[0.2,\"#de77ae\"],[0.3,\"#f1b6da\"],[0.4,\"#fde0ef\"],[0.5,\"#f7f7f7\"],[0.6,\"#e6f5d0\"],[0.7,\"#b8e186\"],[0.8,\"#7fbc41\"],[0.9,\"#4d9221\"],[1,\"#276419\"]],\"sequential\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]],\"sequentialminus\":[[0.0,\"#0d0887\"],[0.1111111111111111,\"#46039f\"],[0.2222222222222222,\"#7201a8\"],[0.3333333333333333,\"#9c179e\"],[0.4444444444444444,\"#bd3786\"],[0.5555555555555556,\"#d8576b\"],[0.6666666666666666,\"#ed7953\"],[0.7777777777777778,\"#fb9f3a\"],[0.8888888888888888,\"#fdca26\"],[1.0,\"#f0f921\"]]},\"colorway\":[\"#636efa\",\"#EF553B\",\"#00cc96\",\"#ab63fa\",\"#FFA15A\",\"#19d3f3\",\"#FF6692\",\"#B6E880\",\"#FF97FF\",\"#FECB52\"],\"font\":{\"color\":\"#2a3f5f\"},\"geo\":{\"bgcolor\":\"white\",\"lakecolor\":\"white\",\"landcolor\":\"white\",\"showlakes\":true,\"showland\":true,\"subunitcolor\":\"#C8D4E3\"},\"hoverlabel\":{\"align\":\"left\"},\"hovermode\":\"closest\",\"mapbox\":{\"style\":\"light\"},\"margin\":{\"b\":0,\"l\":0,\"r\":0,\"t\":30},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"white\",\"polar\":{\"angularaxis\":{\"gridcolor\":\"#EBF0F8\",\"linecolor\":\"#EBF0F8\",\"ticks\":\"\"},\"bgcolor\":\"white\",\"radialaxis\":{\"gridcolor\":\"#EBF0F8\",\"linecolor\":\"#EBF0F8\",\"ticks\":\"\"}},\"scene\":{\"xaxis\":{\"backgroundcolor\":\"white\",\"gridcolor\":\"#DFE8F3\",\"gridwidth\":2,\"linecolor\":\"#EBF0F8\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"#EBF0F8\"},\"yaxis\":{\"backgroundcolor\":\"white\",\"gridcolor\":\"#DFE8F3\",\"gridwidth\":2,\"linecolor\":\"#EBF0F8\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"#EBF0F8\"},\"zaxis\":{\"backgroundcolor\":\"white\",\"gridcolor\":\"#DFE8F3\",\"gridwidth\":2,\"linecolor\":\"#EBF0F8\",\"showbackground\":true,\"ticks\":\"\",\"zerolinecolor\":\"#EBF0F8\"}},\"shapedefaults\":{\"line\":{\"color\":\"#2a3f5f\"}},\"ternary\":{\"aaxis\":{\"gridcolor\":\"#DFE8F3\",\"linecolor\":\"#A2B1C6\",\"ticks\":\"\"},\"baxis\":{\"gridcolor\":\"#DFE8F3\",\"linecolor\":\"#A2B1C6\",\"ticks\":\"\"},\"bgcolor\":\"white\",\"caxis\":{\"gridcolor\":\"#DFE8F3\",\"linecolor\":\"#A2B1C6\",\"ticks\":\"\"}},\"title\":{\"x\":0.05},\"xaxis\":{\"automargin\":true,\"gridcolor\":\"#EBF0F8\",\"linecolor\":\"#EBF0F8\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"#EBF0F8\",\"zerolinewidth\":2},\"yaxis\":{\"automargin\":true,\"gridcolor\":\"#EBF0F8\",\"linecolor\":\"#EBF0F8\",\"ticks\":\"\",\"title\":{\"standoff\":15},\"zerolinecolor\":\"#EBF0F8\",\"zerolinewidth\":2}}},\"yaxis\":{\"title\":{\"text\":\"Marginal Events (Conversions)\"},\"zeroline\":true,\"zerolinecolor\":\"black\"},\"title\":{\"text\":\"Marginal Events by Index-to-Control (ITC) Value\"},\"xaxis\":{\"title\":{\"text\":\"ITC Value\"}},\"bargap\":0.3},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('a47c3ac4-8745-4e2a-8f1d-7f19e5a9494d');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n:::\n:::\n\n\n<br>\n\n\n# Conclusion  \n\n**Big Swing** experiments run faster and deliver greater average value. While many attempts miss, rare breakthroughs generate such huge gains that they transform the overall outcome. Strikeouts are common, but home runs change the game --- making bold bets a highly efficient strategy when traffic and time are limited.  \n\n# Recommendation  \n\nPrioritize bold bets to capture this speed and upside, but manage them within a balanced portfolio. Transformational experiments create breakthroughs; smaller wins provide stability. Together, this mix keeps experimentation fast and sustainable.\n\n> Bold swings drive breakthroughs; balance makes them sustainable.\n\n\n# Acknowledgements\n\nBig THANK YOU to my colleague Joseph Powers, PhD, who introduced me to Quarto and using simulation studies to make my work life easier.\n\n---\n\n\n::: {.callout-note collapse=\"false\" icon=\"💬\" title=\"<b>About Me</b>\"}\n\n<div style=\"font-size: 110%\">\n\nI work on experimentation systems, Bayesian optimization, and simulation-driven decision-making. My recent work includes Bayesian long-term optimization, informed priors, and CUPED.\n\nIf you're thinking about experimentation strategy, simulation design, or testing frameworks — I'd love to connect. Always happy to trade ideas or dig deeper into what drives meaningful impact.\n\n📩 **Email:** [rzaliznyak@gmail.com](mailto:rzaliznyak@gmail.com)\n\n</div>\n\n:::\n\n",
    "supporting": [
      "big-swings_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}